### ISSUE TITLE
Function Builder master checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/function-builder#2]
## Design
- [x] **Design doc created** (Date: 7/22/2014) 
 - [x] Make phethelp@gmail.com owner, share with phet-team
 - [x] Add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //) 
- [x] **Mockups complete** (Date: //) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 07/07/16) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 7/10/16) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [ ] Activities and gooru spreadsheet
  - [x] Notify translators?
  - [ ] Sim primer
  - [x] Verify credits
- [x] **Add to Edmodo**
- [ ] **Hold postmortem if applicable** (Date: //) 

## Implementation
- [x] **Sim repo created** (Date: 01/06/15) 
  - [x] Simula-rasa used to create basic project structure
  - [x] Grunt unpublished-readme run to create the initial readme file
  - [x] Collaborators added (such as QA team, designers, etc) 
  - [x] Sim added to active repos list in chipper
  - [x] Standard label set applied
  - [x] Sim suggestions doc reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo
- [x] **Initial development started** (Date: 9/11/15)
- [x] **Sim feature complete** (Date: 06/23/16) 
- [x] **Code review complete** (Date: 07/06/16) 
  - [x] Code review checklist
  - [x] Model description (Date: 07/01/16) 
- [x] **Published** (Date: 7/13/16) 
  - [x] Update repo README to published template

## QA
- [x] **Dev testing complete** (Date: 6/24/16) 
- [x] **First release candidate** (Date: 7/11/16) 
- [x] Test matrix deemed complete (Date: 7/13/16)

**Comment by pixelzoom** [comment]
@ariel-phet Can you comment on why this is labeled "developer-meeting"?

**Comment by ariel-phet** [comment]
Because it was a black and white label....and I accidentally put that instead of master checklist :facepunch:

**Comment by pixelzoom** [comment]
As of 7/13/16, all development tasks on this checklist have been completed.

**Comment by ariel-phet** [comment]
@amanda-phet I believe all that is left here is to upload an activity and do the sim primer(understood if that will be a bit of time from now)

**Comment by pixelzoom** [comment]
> @amanda-phet I believe all that is left here is to upload an activity and do the sim primer(understood if that will be a bit of time from now)

If it's going to be a bit of time, then let's create an issue specifically for that, then close this issue.

**Comment by amanda-phet** [comment]
That's fine with me. I'm not sure if primers will ever be finished at the same time a sim is being published, so I'm not sure it makes sense to have on this master checklist, but we should check with Amy H about that. I'll close this issue.
